name: Build Marp Presentation

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Copy assets for build
        run: |
          # Create a temporary directory next to the presentation for building
          mkdir -p presentations/assets
          cp -r assets/* presentations/assets/
          # Update image paths in the markdown
          sed -i 's|"\.\./assets/|"./assets/|g' presentations/nim-presentation.md

      - name: Build HTML
        run: npm run build:html

      - name: Build PDF
        run: npm run build:pdf

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment directory
        run: |
          mkdir -p _site
          cp presentations/nim-presentation.html _site/index.html
          # Copy assets to the root of the site
          cp -r assets _site/ || true
          cp -r themes _site/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4