name: Build Marp Presentation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: List presentations and themes directories
        run: |
          ls -l presentations/
          ls -l themes/

      - name: Build HTML
        run: npm run build:html

      - name: Build PDF
        run: npm run build:pdf

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: nim-presentation-html
          path: |
            presentations/nim-presentation.html
            assets/**

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: nim-presentation-pdf
          path: presentations/nim-presentation.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build HTML
        run: npm run build:html

      - name: Prepare publish directory
        run: |
          mkdir gh-pages
          cp presentations/nim-presentation.html gh-pages/index.html
          cp -r assets gh-pages/assets

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages 